### PR TITLE
feat(common): add doc urls to analyticsWaveApi method jsdocs

### PR DESCRIPTION
**Pull request by smithgp**
### What does this PR do?

Add doc links to the jsdoc for the `analyticsWaveApi` methods now that they're public.

### What issues does this PR fix or reference?

@W-9556613@

cc: @mblumreich, @ychhetri, @reidaelliott, @karihotchkiss, @jolley-sfdc

### CODE REVIEW

**Review by randi274 — APPROVED** [review]
Looks good, and nice change to get the docs added! I am getting redirected for all of these links, but they all work and correspond to their given articles. For instance: 

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/reference_analytics_delete_dataset.html
- becomes ->
https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_analytics_delete_dataset

As long as that change is what you're expecting, it works for me!

**Comment by smithgp** [comment]
Oh, good catch. I copied the links out of https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_lightning_analytics_wave_api, which has them with `.html`, but the tree on the docs site has them w/o the `.html`. I think I'll remove the `.html` to match what the other various `ui*Api` jsdoc has.

**Comment by ychhetri** [comment]
Thanks Greg for making this change!

**Review by ychhetri — APPROVED** [review]

**Comment by smithgp** [comment]
@randi274 - I don't have write access so I can't merge this myself, can you? Thanks!

**Pull request merged**
