### PR TITLE
chore: update lwc versions

### PR DESCRIPTION
**Pull request by jye-sf**
### What does this PR do?
PR updates the lwc, engine, errors, and template-compiler versions to the latest in preparation for the next major release.

### What issues does this PR fix or reference?
Includes updates made to various warnings and errors and adds support for new directives added to the compiler.

This change is needed for the 242 release.

### CODE REVIEW

**Comment by jye-sf** [comment]
What's the timeline for releasing the language server for 242, and what should a platform customer do to get access to the version containing these changes when that is released?

We would like this information so we can include it in our documentation around the new compiler features. Thanks!

**Comment by randi274** [comment]
@jye-sf in working with the LWC team, we were informed there were some major changes we'll need to make to consume the latest in the LWC compiler. This is in our backlog to address soon though! Which changes were you able to address with the version bumps here?

**Comment by jye-sf** [comment]
Hey @randi274, these version bumps address the "Invalid directive" error we get when using the new LWC directives we plan on releasing in 242:
image
After updating these versions, I no longer get these errors when launching the "Launch DX - Aura & LWC" workspace.
Screen Shot 2022-10-24 at 1 50 07 PM

I believe there were conversations in the past about the major changes needed to upgrade the lwc compiler version [here](https://github.com/forcedotcom/lightning-language-server/blob/main/packages/lwc-language-server/package.json#L26). I believe that's still needed so we're not so far behind the latest, but it looks like that work isn't needed to resolve these specific errors.

**Comment by randi274** [comment]
Great, thanks for the clarification! We'll bring this one in and get it ready for review 👍

**Comment by randi274** [comment]
This has been merged with #518 with details on QA there - we'll also update VS Code in the next release or two so that'll be queued up and ready once it's GA. Thanks for contributing this and getting us one step closer to caught up with the latest and greatest for the LWC libraries!

**Pull request closed without merging**
